#
# Test Jekyll syntax for issues
#

name: Jekyll site CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'MarlinFirmware/MarlinDocumentation'
    steps:
    - uses: actions/checkout@v2
    - name: Jekyll Test Build
      uses: fabacab/jekyll-builder-for-github-pages-action@v1
      #uses: PaulRosenthal/Jekyll-Deploy-Test-Action@v1
